#!/bin/bash
#
# ProviewR   Open Source Process Control.
# Copyright (C) 2005-2020 SSAB EMEA AB.
#
# This file is part of ProviewR.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ProviewR. If not, see <http://www.gnu.org/licenses/>
#
# Linking ProviewR statically or dynamically with other modules is
# making a combined work based on ProviewR. Thus, the terms and
# conditions of the GNU General Public License cover the whole
# combination.
#
# In addition, as a special exception, the copyright holders of
# ProviewR give you permission to, from the build function in the
# ProviewR Configurator, combine ProviewR with modules generated by the
# ProviewR PLC Editor to a PLC program, regardless of the license
# terms of these modules. You may copy and distribute the resulting
# combined work under the terms of your choice, provided that every
# copy of the combined work is accompanied by a complete copy of
# the source code of ProviewR (the version used to produce the
# combined work), being distributed under the terms of the GNU
# General Public License plus this exception.
#
#
# pwr_cleanup.sh
#
# NOTE! This file removes all IPC objects for the user.
# 	If you have other program which creates IPC objects,
#	then do not use this script

uid=`id -u`


function extract_cols(){

filename=$1           #/proc/sysvipc/shm
colname1=$2		#"uid"
colname2=$3		#"shmid"
header=true
N=0

result=""

while read -r line;
do
	if $header
	then
		arr=($line)
		for i in "${!arr[@]}"; do
			if [[ "${arr[$i]}" = "${colname1}" ]]; then
				N1=$i;
			fi
			if [[ "${arr[$i]}" = "${colname2}" ]]; then
				N2=$i;
			fi
		done
		header=false
	else
		arr=($line)
		#	echo "${arr[$N]}";
		result="$result ${arr[$N1]} ${arr[$N2]}\n"
	fi
done < $filename

printf "$result"
}

# remove semaphores
eval `extract_cols /proc/sysvipc/sem uid semid |grep "$uid "|awk '{printf "ipcrm sem %s;", $2}'`

# remove message queues
eval `extract_cols /proc/sysvipc/msg uid msqid |grep "$uid "|awk '{printf "ipcrm msg %s;", $2}'`

# remove shared memory
eval `extract_cols /proc/sysvipc/shm uid shmid |grep "$uid "|awk '{printf "ipcrm shm %s;", $2}'`

tmpdir='/tmp/'

if [ $TMPDIR ]; 
then 
	tmpdir=$TMPDIR
fi

rm $tmpdir/pwr*$PWR_BUS_ID
